import { Inter } from "next/font/google";
import "./globals.css";
import Categories from "./components/Categories";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="parent">
          <div className="contentContainer">{children}</div>
          <div className="categoryContainer">
            <Categories />
          </div>
        </div>
      </body>
    </html>
  );
}
